import { t } from 'i18next';

export const labelNameMap: { [key: string]: string } = {
  boring: t('feedback-utils.boring'),
  not_boring: t('feedback-utils.not-boring'),
  inaccurate: t('feedback-utils.not-true'),
  not_inaccurate: t('feedback-utils.true'),
  repetitive: t('feedback-utils.repetitive'),
  not_repetitive: t('feedback-utils.not-repetitive'),
  out_of_character: t('feedback-utils.out-of-character'),
  not_out_of_character: t('feedback-utils.not-out-of-character'),
  bad_memory: t('feedback-utils.bad-memory'),
  not_bad_memory: t('feedback-utils.not-bad-memory'),
  long: t('feedback-utils.too-long'),
  not_long: t('feedback-utils.not-too-long'),
  short: t('feedback-utils.too-short'),
  not_short: t('feedback-utils.not-too-short'),
  ends_chat_early: t('feedback-utils.ends-chat-early'),
  not_ends_chat_early: t('feedback-utils.not-ends-chat-early'),
  funny: t('feedback-utils.funny'),
  not_funny: t('feedback-utils.not-funny'),
  interesting: t('feedback-utils.interesting'),
  not_interesting: t('feedback-utils.not-interesting'),
  helpful: t('feedback-utils.helpful'),
  not_helpful: t('feedback-utils.not-helpful'),
  voice_wrong_voice: t('feedback-utils.voice-wrong-voice'),
  voice_low_quality: t('feedback-utils.voice-low-quality'),
  voice_incorrect_pronounciation: t(
    'feedback-utils.voice-incorrect-pronounciation',
  ),
  voice_repeated_words: t('feedback-utils.voice-repeated-words'),
  voice_missing_words: t('feedback-utils.voice-missing-words'),
  voice_too_fast: t('feedback-utils.voice-too-fast'),
  voice_too_slow: t('feedback-utils.voice-too-slow'),
  annotations_sexually_suggestive: t(
    'feedback-utils.annotations-sexually-suggestive',
  ),
  annotations_repetitive: t('feedback-utils.annotations-repetitive'),
  annotations_nonsense: t('feedback-utils.annotations-nonsense'),
  annotations_looping: t('feedback-utils.annotations-looping'),
  annotations_out_of_character: t(
    'feedback-utils.annotations-out-of-character',
  ),
  annotations_porn: t('feedback-utils.annotations-porn'),
  annotations_racist: t('feedback-utils.annotations-racist'),
  annotations_disturbing: t('feedback-utils.annotations-disturbing'),
  annotations_harmful_promotes_selfharm: t(
    'feedback-utils.annotations-harmful-promotes-selfharm',
  ),
  annotations_harmful_promotes_terrorism: t(
    'feedback-utils.annotations-harmful-promotes-terrorism',
  ),
  annotations_inaccurate: t('feedback-utils.annotations-inaccurate'),
  annotations_forgets_context: t('feedback-utils.annotations-forgets-context'),
  annotations_technology: t('feedback-utils.annotations-technology'),
  annotations_writing: t('feedback-utils.annotations-writing'),
  annotations_math: t('feedback-utils.annotations-math'),
  annotations_science: t('feedback-utils.annotations-science'),
  annotations_social_studies: t('feedback-utils.annotations-social_studies'),
  annotations_code: t('feedback-utils.annotations-code'),
  annotations_business: t('feedback-utils.annotations-business'),
  annotations_philosophy: t('feedback-utils.annotations-philosophy'),
  annotations_language_learning: t(
    'feedback-utils.annotations-language-learning',
  ),
  annotations_emotional_support: t(
    'feedback-utils.annotations-emotional-support',
  ),
  annotations_friendship: t('feedback-utils.annotations-friendship'),
  annotations_planning: t('feedback-utils.annotations-planning'),
  annotations_life_advice: t('feedback-utils.annotations-life-advice'),
  annotations_recommendation: t('feedback-utils.annotations-recommendation'),
  annotations_fitness: t('feedback-utils.annotations-fitness'),
  annotations_cooking: t('feedback-utils.annotations-cooking'),
  annotations_interactive_story_telling: t(
    'feedback-utils.annotations-interactive-story-telling',
  ),
  annotations_story_telling: t('feedback-utils.annotations-story-telling'),
  annotations_comedy: t('feedback-utils.annotations-comedy'),
  annotations_discussion: t('feedback-utils.annotations-discussion'),
  annotations_gameplay: t('feedback-utils.annotations-gameplay'),
};

export const goodFeedbackLabels = ['funny', 'interesting', 'helpful'];
export const badFeedbackLabels = [
  'boring',
  'inaccurate',
  'repetitive',
  'out_of_character',
  'bad_memory',
  'long',
  'short',
  'ends_chat_early',
];

export const badVoiceLabels = [
  'voice_wrong_voice',
  'voice_low_quality',
  'voice_incorrect_pronounciation',
  'voice_repeated_words',
  'voice_missing_words',
  'voice_too_fast',
  'voice_too_slow',
];
